version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: database_development
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: "exit 0"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3001
      - JWT_KEY=supersecretkey_example
      - DEV_DB_USERNAME=root
      - DEV_DB_PASSWORD=rootpassword
      - DEV_DB_NAME=database_development
      - DEV_DB_HOSTNAME=db
      - DEV_DB_DIALECT=mysql
      - DEV_DB_LOGGIN=true
    healthcheck:
      test: "exit 0"

volumes:
  db_data:
